name: CI
on:
  push:
    branches:
      - main
      - develop*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - develop*
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, windows-2019, windows-2022 ]
        # path: [ absolute, relative, tilde, default ]
        # setvars: [ 'true', 'false' ]
        include:
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/IRC_NAS/2a13d966-fcc5-4a66-9fcc-50603820e0c9/w_HPCKit_p_2023.1.0.46357_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/19085/w_HPCKit_p_2023.0.0.25931_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18976/w_HPCKit_p_2022.3.1.19755_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18857/w_HPCKit_p_2022.3.0.9564_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/IRC_NAS/18680/w_HPCKit_p_2022.2.0.173_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18578/w_HPCKit_p_2022.1.3.145_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18529/w_HPCKit_p_2022.1.2.116_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18417/w_HPCKit_p_2022.1.0.93_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18247/w_HPCKit_p_2021.4.0.3340_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/17940/w_HPCKit_p_2021.3.0.3227_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/17762/w_HPCKit_p_2021.2.0.2901_offline.exe'}
          - {os: windows-2019, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/17392/w_HPCKit_p_2021.1.0.2682_offline.exe'}

          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/IRC_NAS/2a13d966-fcc5-4a66-9fcc-50603820e0c9/w_HPCKit_p_2023.1.0.46357_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/19085/w_HPCKit_p_2023.0.0.25931_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18976/w_HPCKit_p_2022.3.1.19755_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18857/w_HPCKit_p_2022.3.0.9564_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/IRC_NAS/18680/w_HPCKit_p_2022.2.0.173_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18578/w_HPCKit_p_2022.1.3.145_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18529/w_HPCKit_p_2022.1.2.116_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18417/w_HPCKit_p_2022.1.0.93_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/18247/w_HPCKit_p_2021.4.0.3340_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/17940/w_HPCKit_p_2021.3.0.3227_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/17762/w_HPCKit_p_2021.2.0.2901_offline.exe'}
          # - {os: windows-2022, path: default, setvars: true, windows_url: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/17392/w_HPCKit_p_2021.1.0.2682_offline.exe'}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set bin path
        if: runner.os != 'Windows'
        run: |
          if [ "${{ matrix.path }}" == "absolute" ]; then
            bindir="$HOME/.local/bin"
          elif [ "${{ matrix.path }}" == "relative" ]; then
            bindir="bin"
          elif [ "${{ matrix.path }}" == "tilde" ]; then
            bindir="~/.local/bin"
          else
            # action's default location
            bindir="~/.local/bin/ifort"
          fi

          echo "TEST_BINDIR=$bindir" >> $GITHUB_ENV

      - name: Set bin path (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if ("${{ matrix.path }}" -eq "absolute") {
            # $bindir = "C:\Users\runneradmin\.local\bin"
            $bindir = "C:\Program Files (x86)\Intel\oneAPI"
          } elseif ("${{ matrix.path }}" -eq "relative") {
            $bindir = "bin"
          } elseif ("${{ matrix.path }}" -eq "tilde") {
            $bindir = "~/.local/bin"
          } else {
            # actions's default location
            $bindir = "~/.local/bin/ifort"
          }

          echo "TEST_BINDIR=$bindir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install compilers
        if: matrix.path != 'default'
        uses: ./
        with:
          path: ${{ env.TEST_BINDIR }}
          setvars: ${{ matrix.setvars }}

      - name: Install compilers
        if: matrix.path == 'default'
        uses: ./
        with:
          setvars: ${{ matrix.setvars }}
          windows_url: ${{ matrix.windows_url }}

      # - name: Set environment variables
      #   if: runner.os != 'Windows' && matrix.setvars != 'true'
      #   shell: bash
      #   run: |
      #     source "$INTEL_HPCKIT_INSTALL_PATH/setvars.sh"
      #     env | grep oneapi >> $GITHUB_ENV

      # - name: Set environment variables
      #   if: runner.os == 'Windows' && matrix.setvars != 'true'
      #   shell: cmd
      #   run: |
      #     call "%INTEL_HPCKIT_INSTALL_PATH%\compiler\%INTEL_COMPILER_VERSION%\env\vars.bat"
      #     set | findstr /c:"oneAPI" >> "%GITHUB_ENV%"

      # # not needed atm, but just in case any future tests require this
      # - name: Set SETVARS_COMPLETED
      #   if: matrix.setvars != 'true'
      #   shell: bash
      #   run: echo "SETVARS_COMPLETED=1" >> $GITHUB_ENV

      # - name: Test compilers (Linux & Mac)
      #   if: runner.os != 'Windows'
      #   run: ./test/test.sh ${{ env.TEST_BINDIR }}

      - name: Test compilers (Windows bash)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          if command -v ifort &> /dev/null
          then
            echo "ifort found"
          else
            echo "ifort not available"
            exit 1
          fi

          ifort test/hw.f90 -o hw
          output=$(./hw '2>&1')
          if [[ "$output" == *"hello world"* ]]
          then
            echo "compile succeeded"
            echo "$output"
          else
            echo "unexpected output: $output"
            exit 1
          fi

      - name: Test compilers (Windows pwsh)
        if: runner.os == 'Windows'
        shell: pwsh
        run: ./test/test.ps1 "${{ env.TEST_BINDIR }}"

      - name: Test compilers (Windows cmd)
        if: runner.os == 'Windows'
        shell: cmd
        run: call "./test/test.bat"