name: Docker images
on:
  push:
    branches:
      - main
      - develop*
      - ci-diagnose*
  pull_request:
    branches:
      - main
      - develop*
jobs:
  test:
    name: Test
    runs-on: windows-2022
    container:
      image: mcr.microsoft.com/windows/server:ltsc2022
      env:
        FC: ifort
        CC: cl
      volumes:
        - install-intelfortran-action:/install-intelfortran-action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set environment variables
        shell: pwsh
        run: |
          echo "INTEL_ONEAPI_INSTALL_PATH=C:\Program Files (x86)\Intel\oneAPI" | Out-File -FilePath "$env:GITHUB_ENV" -Encoding utf8 -Append
          echo "INTEL_INSTALLER_URL=https://registrationcenter-download.intel.com/akdlm/irc_nas/18996/w_fortran-compiler_p_2022.2.1.19749.exe" | Out-File -FilePath "$env:GITHUB_ENV" -Encoding utf8 -Append

      - name: Install Intel Fortran
        shell: cmd
        run: |
          .github/scripts/install_windows.bat
          call "install-intelfortran-action\scripts\install_windows.bat" "${{ env.INTEL_ONEAPI_INSTALL_PATH }}" "${{ env.INTEL_INSTALLER_URL }}"
          
          curl.exe --output %TEMP%\webimage.exe --url %INTEL_INSTALLER_URL% --retry 5 --retry-delay 5
          start /b /wait %TEMP%\webimage.exe -s -x -f webimage_extracted --log extract.log
          del %TEMP%\webimage.exe
          webimage_extracted\bootstrapper.exe -s --action install --eula=accept -p=NEED_VS2017_INTEGRATION=0 -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=0 --log-dir=. --install-dir %INTEL_ONEAPI_INSTALL_PATH%
          rd /s/q "webimage_extracted"